name: dart_image_grabber
description: Download images from a web page.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.18.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  http: ^0.13.6
  html: ^0.15.4
  path: ^1.8.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
